# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_manager', '0013_auto_20170522_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalannotationstep',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalannotationstep',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[(b'BAD_QUALITY', b'Bad image quality'), (b'BAD_ROIS', b'Wrong or inaccurate ROIs'), (b'OTHER', b'Other (see notes)')], default=None, max_length=20, null=True),
        ),
    ]
