# -*- coding: utf-8 -*-

#  Copyright (c) 2019, CRS4
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to deal in
#  the Software without restriction, including without limitation the rights to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
#  the Software, and to permit persons to whom the Software is furnished to do so,
#  subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
#  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
#  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
#  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Generated by Django 1.11.3 on 2017-07-19 08:25
from __future__ import unicode_literals

from django.db import migrations


def create_reviews_comparisons(apps, schema_editor):
    ROIsAnnotation = apps.get_model('reviews_manager', 'ROIsAnnotation')
    ReviewsComparison = apps.get_model('reviews_manager', 'ReviewsComparison')
    for annotation in ROIsAnnotation.objects.all():
        for steps in annotation.steps.all():
            clinical_annotation_steps = steps.clinical_annotation_steps.all()
            comparison_obj = ReviewsComparison(
                review_1=clinical_annotation_steps[0],
                review_2=clinical_annotation_steps[1]
            )
            comparison_obj.save()


def drop_reviews_comparisons(apps, schema_editor):
    ReviewsComparison = apps.get_model('reviews_manager', 'ReviewsComparison')
    ReviewsComparison.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_manager', '0015_auto_20170719_1248'),
    ]

    operations = [
        migrations.RunPython(create_reviews_comparisons, drop_reviews_comparisons)
    ]
