# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 08:25
from __future__ import unicode_literals

from django.db import migrations


def create_reviews_comparisons(apps, schema_editor):
    ROIsAnnotation = apps.get_model('reviews_manager', 'ROIsAnnotation')
    ReviewsComparison = apps.get_model('reviews_manager', 'ReviewsComparison')
    for annotation in ROIsAnnotation.objects.all():
        for steps in annotation.steps.all():
            clinical_annotation_steps = steps.clinical_annotation_steps.all()
            comparison_obj = ReviewsComparison(
                review_1=clinical_annotation_steps[0],
                review_2=clinical_annotation_steps[1]
            )
            comparison_obj.save()


def drop_reviews_comparisons(apps, schema_editor):
    ReviewsComparison = apps.get_model('reviews_manager', 'ReviewsComparison')
    ReviewsComparison.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_manager', '0015_auto_20170719_1248'),
    ]

    operations = [
        migrations.RunPython(create_reviews_comparisons, drop_reviews_comparisons)
    ]
