# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_manager', '0016_auto_20170719_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewscomparison',
            name='positive_quality_control',
            field=models.NullBooleanField(default=None),
        ),
    ]
