# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_manager', '0017_reviewscomparison_positive_quality_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalannotation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_annotations', to='slides_manager.Case'),
        ),
        migrations.AlterField(
            model_name='clinicalannotationstep',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_annotations', to='slides_manager.Slide'),
        ),
        migrations.AlterField(
            model_name='roisannotation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roi_annotations', to='slides_manager.Case'),
        ),
        migrations.AlterField(
            model_name='roisannotationstep',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roi_annotations', to='slides_manager.Slide'),
        ),
        migrations.AlterUniqueTogether(
            name='roisannotation',
            unique_together=set([]),
        ),
    ]
