# Generated by Django 3.1.13 on 2021-10-26 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0019_auto_20210424_1321'),
        ('predictions_manager', '0002_auto_20210915_1608'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_manager', '0019_auto_20210424_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('completion_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='predictions_manager.prediction')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prediction_reviews', to='slides_manager.slide')),
            ],
        ),
    ]
