# Generated by Django 3.1.13 on 2022-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_manager', '0020_predictionreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalannotationstep',
            name='faded_staining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalannotationstep',
            name='out_of_focus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clinicalannotationstep',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('BAD_STAINING', 'Faded staining'), ('BAD_FOCUS', 'Non uniform focus'), ('BAD_QUALITY', 'Bad image quality'), ('BAD_ROIS', 'Wrong or inaccurate ROIs'), ('OTHER', 'Other (see notes)')], default=None, max_length=20, null=True),
        ),
    ]
