title: CRS4 Digital Pathology Platform
description: Documentation for the CRS4 Digital Pathology Platform (CDPP)
theme: just-the-docs

url: ""
# baseurl: "/cdpp-docs"

search_enabled: true

aux_links:
  "CRS4 on GitHub":
    - "https://github.com/crs4"

nav_sort: case_insensitive

includes:
  head: head_custom.html
  