# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0002_focusregionannotation_ductal_carcinoma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreannotation',
            name='gleason_4_percentage',
        ),
    ]
