# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0003_remove_coreannotation_gleason_4_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='small_cell_signer_ring',
            new_name='small_cell_signet_ring',
        ),
    ]
