# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0004_auto_20170306_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusregionannotation',
            name='cells_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='focusregionannotation',
            name='cellular_density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='focusregionannotation',
            name='cellular_density_helper_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='focusregionannotation',
            name='gleason_4_path_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
