# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0005_auto_20170310_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusregionannotation',
            name='gleason_4_cells_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='gleason_4_cellular_density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='gleason_4_cellular_density_helper_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
