# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 08:26
from __future__ import unicode_literals

from django.db import migrations


def create_gleason_4_elements(apps, schema_editor):
    FocusRegionAnnotation = apps.get_model('clinical_annotations_manager', 'FocusRegionAnnotation')
    Gleason4Element = apps.get_model('clinical_annotations_manager', 'Gleason4Element')
    for annotation in FocusRegionAnnotation.objects.all():
        if annotation.gleason_4_path_json:
            g4_element = Gleason4Element(
                json_path=annotation.gleason_4_path_json,
                area=annotation.gleason_4_area,
                cellular_density_helper_json=annotation.gleason_4_cellular_density_helper_json,
                cellular_density=annotation.gleason_4_cellular_density,
                cells_count=annotation.gleason_4_cells_count,
                focus_region_annotation=annotation
            )
            g4_element.save()


def reverse_create_gleason_4_elements(apps, schema_editor):
    Gleason4Element = apps.get_model('clinical_annotations_manager', 'Gleason4Element')
    Gleason4Element.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0007_gleason4element'),
    ]

    operations = [
        migrations.RunPython(create_gleason_4_elements, reverse_create_gleason_4_elements),
    ]
