# -*- coding: utf-8 -*-

#  Copyright (c) 2019, CRS4
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to deal in
#  the Software without restriction, including without limitation the rights to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
#  the Software, and to permit persons to whom the Software is furnished to do so,
#  subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
#  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
#  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
#  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Generated by Django 1.10.5 on 2017-04-11 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0008_auto_20170405_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_area',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_cells_count',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_cellular_density',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_cellular_density_helper_json',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_path_json',
        ),
    ]
