# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0008_auto_20170405_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_area',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_cells_count',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_cellular_density',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_cellular_density_helper_json',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='gleason_4_path_json',
        ),
    ]
