# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 16:06
from __future__ import unicode_literals

from django.db import migrations


def move_g4_elements(apps, schema_editor):
    Gleason4Element = apps.get_model('clinical_annotations_manager', 'Gleason4Element')
    GleasonElement = apps.get_model('clinical_annotations_manager', 'GleasonElement')
    FocusRegionAnnotation = apps.get_model('clinical_annotations_manager', 'FocusRegionAnnotation')
    for g4_element in Gleason4Element.objects.all():
        gleason_element = GleasonElement(
            json_path=g4_element.json_path,
            area=g4_element.area,
            cellular_density_helper_json=g4_element.cellular_density_helper_json,
            cellular_density=g4_element.cellular_density,
            cells_count=g4_element.cells_count,
            focus_region_annotation=FocusRegionAnnotation.objects.get(pk=g4_element.focus_region_annotation_id),
            gleason_type='G4'
        )
        gleason_element.save()


def reverse_move_g4_elements(apps, schema_editor):
    GleasonElement = apps.get_model('clinical_annotations_manager', 'GleasonElement')
    GleasonElement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0010_gleasonelement'),
    ]

    operations = [
        migrations.RunPython(move_g4_elements, reverse_move_g4_elements)
    ]
