# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0011_auto_20170414_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gleason4element',
            name='focus_region_annotation',
        ),
        migrations.DeleteModel(
            name='Gleason4Element',
        ),
    ]
