# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0012_auto_20170418_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusregionannotation',
            name='adenosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='atrophic_lesions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='inflammation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='pah',
            field=models.BooleanField(default=False),
        ),
    ]
