# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-03 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0013_auto_20181015_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gleasonelement',
            name='gleason_type',
            field=models.CharField(choices=[(b'G1', b'GLEASON 1'), (b'G2', b'GLEASON 2'), (b'G3', b'GLEASON 3'), (b'G4', b'GLEASON 4'), (b'G5', b'GLEASON 5')], max_length=2),
        ),
    ]
