# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-10 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0014_auto_20200603_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='gleasonelement',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
