# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0015_gleasonelement_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreannotation',
            name='creation_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='creation_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='gleasonelement',
            name='creation_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sliceannotation',
            name='creation_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
