# Generated by Django 3.1.7 on 2021-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0016_auto_20201124_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreannotation',
            name='gleason_group',
            field=models.CharField(choices=[('GG1', 'GRADE_GROUP_1'), ('GG2', 'GRADE_GROUP_2'), ('GG3', 'GRADE_GROUP_3'), ('GG4', 'GRADE_GROUP_4'), ('GG5', 'GRADE_GROUP_5')], max_length=3),
        ),
        migrations.AlterField(
            model_name='gleasonelement',
            name='gleason_type',
            field=models.CharField(choices=[('G1', 'GLEASON 1'), ('G2', 'GLEASON 2'), ('G3', 'GLEASON 3'), ('G4', 'GLEASON 4'), ('G5', 'GLEASON 5')], max_length=2),
        ),
    ]
