# Generated by Django 3.1.13 on 2021-11-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0017_auto_20210424_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreannotation',
            old_name='creation_start_date',
            new_name='action_start_time',
        ),
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='creation_start_date',
            new_name='action_start_time',
        ),
        migrations.RenameField(
            model_name='gleasonelement',
            old_name='creation_start_date',
            new_name='action_start_time',
        ),
        migrations.RenameField(
            model_name='sliceannotation',
            old_name='creation_start_date',
            new_name='action_start_time',
        ),
    ]
