# Generated by Django 3.1.13 on 2021-12-06 10:18

from django.db import migrations


def update_action_complete_time(apps, schema_editor):
    GleasonElements = apps.get_model('clinical_annotations_manager', 'GleasonElement')
    for g_element in GleasonElements.objects.all():
        g_element.action_complete_time = g_element.creation_date
        g_element.creation_date = g_element.focus_region_annotation.creation_date
        g_element.save()


def reverse_action_complete_time(apps, schema_editor):
    GleasonElements = apps.get_model('clinical_annotations_manager', 'GleasonElement')
    for g_element in GleasonElements.objects.all():
        g_element.creation_date = g_element.action_complete_time
        g_element.action_complete_time = None
        g_element.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0019_auto_20211201_0933'),
    ]

    operations = [
        migrations.RunPython(update_action_complete_time, reverse_action_complete_time),
    ]
