# Generated by Django 3.1.13 on 2021-12-07 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0020_auto_20211206_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliceannotation',
            name='intraglandular_inflammation',
        ),
        migrations.RemoveField(
            model_name='sliceannotation',
            name='pah',
        ),
        migrations.RemoveField(
            model_name='sliceannotation',
            name='periglandular_inflammation',
        ),
        migrations.RemoveField(
            model_name='sliceannotation',
            name='stromal_inflammation',
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='gleason_four_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
