# Generated by Django 3.1.13 on 2022-10-10 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('clinical_annotations_manager', '0021_auto_20221010_0718'), ('clinical_annotations_manager', '0022_auto_20221010_0858')]

    dependencies = [
        ('rois_manager', '0024_auto_20220303_1519'),
        ('clinical_annotations_manager', '0020_auto_20211206_1018'),
        ('reviews_manager', '0020_predictionreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GleasonElement',
            new_name='GleasonPattern',
        ),
        migrations.RenameField(
            model_name='gleasonpattern',
            old_name='json_path',
            new_name='roi_json',
        ),
        migrations.RemoveField(
            model_name='gleasonpattern',
            name='cells_count',
        ),
        migrations.RemoveField(
            model_name='gleasonpattern',
            name='cellular_density',
        ),
        migrations.RemoveField(
            model_name='gleasonpattern',
            name='cellular_density_helper_json',
        ),
        migrations.AddField(
            model_name='gleasonpattern',
            name='annotation_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gleason_annotations', to='reviews_manager.clinicalannotationstep'),
        ),
        migrations.AddField(
            model_name='gleasonpattern',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gleasonpattern',
            name='details_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gleasonpattern',
            name='focus_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gleason_patterns', to='rois_manager.focusregion'),
        ),
        migrations.AddField(
            model_name='gleasonpattern',
            name='label',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='gleasonpattern',
            name='gleason_type',
            field=models.CharField(choices=[('G1', 'GLEASON 1'), ('G2', 'GLEASON 2'), ('G3', 'GLEASON 3'), ('G4', 'GLEASON 4'), ('G5', 'GLEASON 5'), ('ST', 'STROMA'), ('OT', 'OTHER')], max_length=2),
        ),
    ]
