# Generated by Django 3.1.13 on 2021-12-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0021_auto_20211207_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='adenosis',
            new_name='atrophy',
        ),
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='atrophic_lesions',
            new_name='atypical_intraductal_proliferation',
        ),
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='comedo_necrosis',
            new_name='extra_prostatic_extension',
        ),
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='hypernephroid_pattern',
            new_name='perineural_invasion',
        ),
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='inflammation',
            new_name='phlogosis',
        ),
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='pah',
            new_name='small_cell',
        ),
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='perineural_involvement',
            new_name='stroma_rich',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='cells_count',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='cellular_density',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='cellular_density_helper_json',
        ),
        migrations.RemoveField(
            model_name='focusregionannotation',
            name='small_cell_signet_ring',
        ),
    ]
