# Generated by Django 3.1.13 on 2022-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0022_auto_20211210_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusregionannotation',
            old_name='phlogosis',
            new_name='inflammation',
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='acinar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='neuro_endocrine_differentiation',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='pin_like_carcinoma',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='pleomorphic_giant_cell',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='sarcomatoid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='focusregionannotation',
            name='signet_ring_cell',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='focusregionannotation',
            name='small_cell',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
