# Generated by Django 3.1.13 on 2022-10-10 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_manager', '0020_predictionreview'),
        ('rois_manager', '0024_auto_20220303_1519'),
        ('clinical_annotations_manager', '0022_auto_20221010_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gleasonpattern',
            name='annotation_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gleason_annotations', to='reviews_manager.clinicalannotationstep'),
        ),
        migrations.AlterField(
            model_name='gleasonpattern',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='gleasonpattern',
            name='focus_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gleason_patterns', to='rois_manager.focusregion'),
        ),
        migrations.AlterField(
            model_name='gleasonpattern',
            name='gleason_type',
            field=models.CharField(choices=[('G3', 'GLEASON 3'), ('G4', 'GLEASON 4'), ('G5', 'GLEASON 5'), ('ST', 'STROMA'), ('OT', 'OTHER')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gleasonpattern',
            name='label',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='gleasonpattern',
            unique_together={('label', 'annotation_step')},
        ),
        migrations.RemoveField(
            model_name='gleasonpattern',
            name='focus_region_annotation',
        ),
    ]
