# Generated by Django 3.1.13 on 2022-10-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0023_auto_20221010_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='GleasonPatternSubregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('roi_json', models.TextField()),
                ('area', models.FloatField()),
                ('details_json', models.TextField(blank=True, default=None, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('gleason_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='clinical_annotations_manager.gleasonpattern')),
            ],
        ),
    ]
