#  Copyright (c) 2022, CRS4
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to deal in
#  the Software without restriction, including without limitation the rights to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
#  the Software, and to permit persons to whom the Software is furnished to do so,
#  subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
#  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
#  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
#  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Generated by Django 3.1.13 on 2022-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0024_gleasonpatternsubregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gleasonpattern',
            name='gleason_type',
            field=models.CharField(choices=[('G3', 'GLEASON 3'), ('G4', 'GLEASON 4'), ('G5', 'GLEASON 5'), ('ST', 'STROMA'), ('OT', 'OTHER'), ('LG', 'LEGACY')], max_length=2),
        ),
    ]
