# Generated by Django 3.1.13 on 2022-10-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0026_auto_20221031_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gleasonpattern',
            name='gleason_type',
            field=models.CharField(choices=[('G3', 'GLEASON 3'), ('G4', 'GLEASON 4'), ('G5', 'GLEASON 5'), ('LG', 'LEGACY')], max_length=2),
        ),
    ]
