# Generated by Django 3.1.13 on 2022-11-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_annotations_manager', '0027_auto_20221031_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreannotation',
            name='central_maturation',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='extra_cribriform_gleason_score',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='extraprostatic_extension',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='highest_rsg',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='intraluminal_acinar_differentiation_grade',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='intraluminal_secretions',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='nuclear_grade_size',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='perineural_growth_with_cribriform_patterns',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='perineural_invasion',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='predominant_rsg',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='rsg_in_area_of_cribriform_morphology',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='coreannotation',
            name='rsg_within_highest_grade_area',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
