# -*- coding: utf-8 -*-

#  Copyright (c) 2019, CRS4
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to deal in
#  the Software without restriction, including without limitation the rights to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
#  the Software, and to permit persons to whom the Software is furnished to do so,
#  subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
#  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
#  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
#  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Generated by Django 1.11.3 on 2017-08-01 08:00
from __future__ import unicode_literals

from django.db import migrations

from promort import settings as pms

import logging
logger = logging.getLogger('promort')


def create_odin_group(apps, schema_editor):
    logger.info('Creating default group for Odin users (if needed)')
    Group = apps.get_model('auth', 'Group')
    group_name = pms.DEFAULT_GROUPS['odin_members']['name']
    group, created = Group.objects.get_or_create(name=group_name)
    logger.info('Group "%s" --- Created %s', group.name, created)


class Migration(migrations.Migration):

    dependencies = [
        ('worklist_manager', '0002_auto_20170328_0652'),
    ]

    operations = [
        migrations.RunPython(create_odin_group),
    ]
