# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-15 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slides_manager', '0018_auto_20191022_1039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaires_manager.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('completion_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('questionnaire_panel_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_a_steps', to='questionnaires_manager.Questionnaire')),
                ('questionnaire_panel_b', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panel_b_steps', to='questionnaires_manager.Questionnaire')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slides_set_a_label', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('slides_set_b_label', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('step_index', models.IntegerField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='questionnaires_manager.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireStepAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_json', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('questionnaire_answers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='questionnaires_manager.QuestionnaireAnswers')),
                ('questionnaire_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaires_manager.QuestionnaireStep')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('questions_json', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionnairestep',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires_manager.QuestionsSet'),
        ),
        migrations.AddField(
            model_name='questionnairestep',
            name='slides_set_a',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slides_set_a', to='slides_manager.SlidesSet'),
        ),
        migrations.AddField(
            model_name='questionnairestep',
            name='slides_set_b',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slides_set_b', to='slides_manager.SlidesSet'),
        ),
        migrations.AddField(
            model_name='questionnaireanswers',
            name='questionnaire_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaires_manager.QuestionnaireRequest'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnairestepanswers',
            unique_together=set([('questionnaire_answers', 'questionnaire_step')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionnairestep',
            unique_together=set([('questionnaire', 'step_index')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireanswers',
            unique_together=set([('questionnaire_request', 'questionnaire')]),
        ),
    ]
