# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-05 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireanswers',
            old_name='author',
            new_name='reviewer',
        ),
    ]
