# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires_manager', '0003_auto_20210222_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairerequest',
            name='extended_label',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
