# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires_manager', '0005_auto_20210302_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairerequest',
            name='extended_label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
