# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_manager', '0008_auto_20161215_1519'),
        ('rois_manager', '0011_auto_20161215_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slice',
            name='annotation_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slices', to='reviews_manager.ROIsAnnotationStep'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slides_manager.Slide'),
        ),
        migrations.AlterUniqueTogether(
            name='slice',
            unique_together=set([('label', 'annotation_step')]),
        ),
    ]
