# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rois_manager', '0012_auto_20170208_0933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='core',
            unique_together=set([('label', 'slice')]),
        ),
        migrations.AlterUniqueTogether(
            name='focusregion',
            unique_together=set([('label', 'core')]),
        ),
        migrations.RemoveField(
            model_name='core',
            name='annotation_step',
        ),
        migrations.RemoveField(
            model_name='focusregion',
            name='annotation_step',
        )
    ]
