# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rois_manager', '0013_auto_20170208_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='label',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='focusregion',
            name='label',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='slice',
            name='label',
            field=models.CharField(max_length=25),
        ),
    ]
