# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rois_manager', '0014_auto_20171109_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusregion',
            name='tissue_status',
            field=models.CharField(blank=True, choices=[(b'NORMAL', b'Normal'), (b'STRESSED', b'Stressed'), (b'TUMOR', b'Tumor')], max_length=8),
        ),
    ]
