# -*- coding: utf-8 -*-

#  Copyright (c) 2019, CRS4
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to deal in
#  the Software without restriction, including without limitation the rights to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
#  the Software, and to permit persons to whom the Software is furnished to do so,
#  subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
#  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
#  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
#  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Generated by Django 1.11.5 on 2018-10-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


def update_tissue_classification(apps, schema_editor):
    FocusRegion = apps.get_model('rois_manager', 'FocusRegion')

    focus_regions = FocusRegion.objects.all()
    for fr in focus_regions:
        if fr.cancerous_region:
            fr.tissue_status = 'TUMOR'
        else:
            fr.tissue_status = 'NORMAL'
        fr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rois_manager', '0015_focusregion_tissue_status'),
    ]

    operations = [
        migrations.RunPython(update_tissue_classification)
    ]
