# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-10 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rois_manager', '0016_auto_20181009_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusregion',
            name='tissue_status',
            field=models.CharField(choices=[(b'NORMAL', b'Normal'), (b'STRESSED', b'Stressed'), (b'TUMOR', b'Tumor')], max_length=8),
        ),
    ]
