# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-10 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rois_manager', '0017_auto_20181010_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusregion',
            name='cancerous_region',
        ),
    ]
