# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rois_manager', '0018_remove_focusregion_cancerous_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='craetion_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='focusregion',
            name='creation_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='creation_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
