# Generated by Django 3.1.13 on 2022-03-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictions_manager', '0003_prediction_review_required'),
        ('rois_manager', '0023_auto_20211201_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='source_collection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cores', to='predictions_manager.tissuefragmentscollection'),
        ),
        migrations.AddField(
            model_name='focusregion',
            name='source_collection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='focus_regions', to='predictions_manager.tissuefragmentscollection'),
        ),
        migrations.AddField(
            model_name='slice',
            name='source_collection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slices', to='predictions_manager.tissuefragmentscollection'),
        ),
    ]
