# .github/workflows/build-gh-pages.yml
name: Build GitHub Pages Site

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site with Jekyll
        run: bundle exec jekyll build
