# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0009_auto_20161215_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidequalitycontrol',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slides_manager.Slide'),
        ),
    ]
