# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0010_auto_20170207_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
