# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0011_auto_20170420_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('label', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='laboratory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='slides_manager.Laboratory'),
        ),
    ]
