# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_manager', '0018_auto_20171128_0956'),
        ('slides_manager', '0012_auto_20170920_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staining', models.CharField(choices=[(b'HE', b'H&E'), (b'TRI', b'Trichrome')], max_length=3)),
                ('adequate_slide', models.BooleanField()),
                ('not_adequacy_reason', models.CharField(blank=True, choices=[(b'BAD_TILES', b'Bad tiles stitching'), (b'BAD_FOCUS', b'Non uniform focus'), (b'DMG_SMP', b'Damaged samples'), (b'OTHER', b'Other (see notes)')], default=None, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('acquisition_date', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rois_annotation_step', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reviews_manager.ROIsAnnotationStep')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slides_manager.Slide')),
            ],
        ),
    ]
