# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0014_auto_20171201_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideevaluation',
            name='rois_annotation_step',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='slide_evaluation', to='reviews_manager.ROIsAnnotationStep'),
        ),
    ]
