# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0015_auto_20171204_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidequalitycontrol',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='slidequalitycontrol',
            name='rois_annotation_step',
        ),
        migrations.RemoveField(
            model_name='slidequalitycontrol',
            name='slide',
        ),
        migrations.DeleteModel(
            name='SlideQualityControl',
        ),
    ]
