# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0016_auto_20171204_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='staining',
        ),
    ]
