# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0017_remove_slide_staining'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesSet',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SlidesSetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_label', models.CharField(max_length=20)),
                ('set_index', models.IntegerField(blank=True, null=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slides_manager.Slide')),
                ('slides_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='slides_manager.SlidesSet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slidessetitem',
            unique_together=set([('slide', 'slides_set', 'set_index'), ('slide', 'slides_set'), ('slide', 'slides_set', 'set_label')]),
        ),
    ]
