# Generated by Django 3.1.7 on 2021-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0018_auto_20191022_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideevaluation',
            name='not_adequacy_reason',
            field=models.CharField(blank=True, choices=[('BAD_TILES', 'Bad tiles stitching'), ('BAD_FOCUS', 'Non uniform focus'), ('DMG_SMP', 'Damaged samples'), ('OTHER', 'Other (see notes)')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='slideevaluation',
            name='staining',
            field=models.CharField(choices=[('HE', 'H&E'), ('TRI', 'Trichrome')], max_length=3),
        ),
    ]
