# Generated by Django 3.1.13 on 2021-12-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0019_auto_20210424_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideevaluation',
            name='not_adequacy_reason',
            field=models.CharField(blank=True, choices=[('BAD_TILES', 'Bad tiles stitching'), ('BAD_FOCUS', 'Non uniform focus'), ('DMG_SMP', 'Damaged samples'), ('NO_CANCER', 'Non-cancer slide'), ('OTHER', 'Other (see notes)')], default=None, max_length=10, null=True),
        ),
    ]
