# Generated by Django 3.1.13 on 2022-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_manager', '0020_auto_20211222_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideevaluation',
            name='not_adequacy_reason',
            field=models.CharField(blank=True, choices=[('BAD_TILES', 'Bad tiles stitching'), ('BAD_STAINING', 'Faded staining'), ('BAD_FOCUS', 'Non uniform focus'), ('DMG_SMP', 'Damaged samples'), ('NO_CANCER', 'Non-cancer slide'), ('OTHER', 'Other (see notes)')], default=None, max_length=15, null=True),
        ),
    ]
